// Constructores de intents del juego (CONTRATOS.md §6.2).
// Canal único de entrada del jugador (§20).

export const INTENT_TYPES = {
  setParam: 'setParam',
  setFault: 'setFault',
  resetFaults: 'resetFaults',
  applyPreset: 'applyPreset',
  action: 'action',
  selectPart: 'selectPart',
  hoverPart: 'hoverPart',
  answer: 'answer',
  useTool: 'useTool',
  removeTool: 'removeTool',
  replacePart: 'replacePart',
  deliver: 'deliver',
  markSuspect: 'markSuspect',
  placePart: 'placePart',
  movePart: 'movePart',
  rotatePart: 'rotatePart',
  deletePart: 'deletePart',
  connect: 'connect',
  disconnect: 'disconnect',
  runTest: 'runTest',
  nextStage: 'nextStage',
  retry: 'retry',
  quit: 'quit',
};

export const intents = {
  setParam: (key, value) => ({ type: INTENT_TYPES.setParam, key, value }),
  setFault: (key, value) => ({ type: INTENT_TYPES.setFault, key, value }),
  resetFaults: () => ({ type: INTENT_TYPES.resetFaults }),
  applyPreset: (presetId) => ({ type: INTENT_TYPES.applyPreset, presetId }),
  action: (name, args = []) => ({ type: INTENT_TYPES.action, name, args }),
  selectPart: (partId) => ({ type: INTENT_TYPES.selectPart, partId: partId ?? null }),
  hoverPart: (partId) => ({ type: INTENT_TYPES.hoverPart, partId: partId ?? null }),
  answer: (choiceId) => ({ type: INTENT_TYPES.answer, choiceId }),
  useTool: (toolId, partId = null) => ({ type: INTENT_TYPES.useTool, toolId, partId }),
  removeTool: (toolId) => ({ type: INTENT_TYPES.removeTool, toolId }),
  replacePart: (partId) => ({ type: INTENT_TYPES.replacePart, partId }),
  deliver: () => ({ type: INTENT_TYPES.deliver }),
  markSuspect: (partId, mark = null) => ({ type: INTENT_TYPES.markSuspect, partId, mark }),
  placePart: (partType, x, y) => ({ type: INTENT_TYPES.placePart, partType, x, y }),
  movePart: (partId, x, y) => ({ type: INTENT_TYPES.movePart, partId, x, y }),
  rotatePart: (partId) => ({ type: INTENT_TYPES.rotatePart, partId }),
  deletePart: (partId) => ({ type: INTENT_TYPES.deletePart, partId }),
  connect: (from, to) => ({ type: INTENT_TYPES.connect, from, to }),
  disconnect: (linkId) => ({ type: INTENT_TYPES.disconnect, linkId }),
  runTest: () => ({ type: INTENT_TYPES.runTest }),
  nextStage: () => ({ type: INTENT_TYPES.nextStage }),
  retry: () => ({ type: INTENT_TYPES.retry }),
  quit: () => ({ type: INTENT_TYPES.quit }),
};
